title: "Seth N.S. Peacock"
description: "B.S. Mathematics, Ohio State University (2024)"
theme: jekyll-theme-minimal

# Optional extras
logo: /assets/profile.jpeg
show_downloads: false
github:
  is_project_page: false